[platformio]
src_dir = src

boards_dir = boards
extra_configs = private_credentials.ini
[env:T5_E_PAPER_S3_V7]
platform = espressif32@6.5.0
board = T5-ePaper-S3
framework = arduino
upload_speed =  921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    ${credentials.build_flags} ;
    -DBOARD_HAS_PSRAM
    -DPSRAM_SPEED=120MHz
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=5
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -Wl,--gc-sections

lib_deps =
    Wire
    SPI
    bblanchon/ArduinoJson @ ^6.21.3